name: 'Deploy Codigo'

on:
  push:
    branches:
      - main

jobs:
  deploy-codigo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Haciendo pull del código"
      - run: echo "Migrando..."
      - run: echo "Generando binarios..."
      - run: echo "Deploying Codigo to production"
